name = "Hermit-V2-fork"
license = "MIT"
licenselink = "https://github.com/matthewharris02/hermit/blob/master/LICENSE"
description = "A minimal and fast hugo theme for bloggers."
homepage = "https://github.com/matthewharris02/hermit-V2"
tags = ["blog", "minimal", "dark", "responsive"]
features = [
  "single column",
  "featured image",
  "social icons",
  "google analytics",
  "disqus",
  "customizable"
]
min_version = 0.43

[author]
  name = "Matthew"
[original]
  name = "Track3"
  homepage = "https://www.xxxlbox.com"
  repo = "https://github.com/Track3/hermit"
